### PR TITLE
fix: Limit event history size

### LINKED ISSUE #75: Protect against Tx record using up too much space
Consider a DoS attack where many transactions are made and the canister storage is filled. Seems this is not protected against.

### PR DESCRIPTION
**Pull request by adamspofford-dfinity**
Previously the wallet would record as many events as it could hold. This could result in a call running out of cycles when the vector needed to be reallocated. This sets a cap on events as 10,000 global events and 1,000 canister-specific events per canister.

Fixes #75.

### CODE REVIEW

File: wallet/src/events.rs [hunk 1]
```diff
@@ -192,12 +205,17 @@ pub fn record(kind: EventKind) {
...
         let mut buffer = buffer.borrow_mut();
-        let len = buffer.len();
+        let buffer = &mut *buffer;
+        let len = buffer.total();
         buffer.push(Event {
             id: len,
             timestamp: api::time() as u64,
             kind,
         });
+        if buffer.events.len() > 10_000 {
```
Comment (ericswanson-dfinity) [inline wallet/src/events.rs:215]: Can we declare these constants somewhere (here, and the 1000 constant) instead of using values here?

File: wallet/src/events.rs [hunk 2]
```diff
@@ -8,11 +8,14 @@ use serde::de::{SeqAccess, Visitor};
...
 use std::cmp::min;
+use std::collections::VecDeque;
 use std::fmt::{self, Formatter};
+use std::ops::Range;
 
 #[derive(CandidType, Clone, Default, Deserialize)]
 pub struct EventBuffer {
-    pub events: Vec<Event>,
+    pub events: VecDeque<Event>,
+    pub culled: Option<usize>,
```
Comment (ericswanson-dfinity) [inline wallet/src/events.rs:18]: 1. What's the rationale for storing this here, as opposed to calculating it (as `total` does)?
2. Does anything special need to happen during upgrade? Unless I'm missing something, I only see it being filled with Some(0), which will be correct for this upgrade, but not for the next one.

Comment (adamspofford-dfinity) [reply wallet/src/events.rs:18]: You're right, I had it in my head before I started implementing it. And if I *were* to keep it, which I'm not, it'll be filled with Some(0), and then the next recorded event would have set it correctly as however many events were culled.

File: wallet/src/events.rs [hunk 3]
```diff
@@ -46,9 +48,8 @@ impl ManagedList {
             id: events.len() as u32,
             timestamp,
         });
-        if events.len() > 1000 {
-            events.drain(..events.len() - 1000);
-            canister.culled = Some(events[0].id as usize);
+        if events.len() > MAX_CANISTER_EVENTS {
+            events.drain(..events.len() - MAX_EVENTS);
```
Comment (ericswanson-dfinity) [inline wallet/src/events.rs:52]: shouldn't these both be using one of the other of MAX_EVENTS or MAX_CANISTER_EVENTS?

Comment (ericswanson-dfinity) [inline wallet/src/events.rs:52]:
```suggestion
            events.drain(..events.len() - MAX_CANISTER_EVENTS);
```

**Review by ericswanson-dfinity — APPROVED** [review]
Looks good.  I think the CI might be stuck because of the path filtering on the shellcheck workflow.
